// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqx88CK-Hj_aRJcF866QDT38WpWmutZ2I',
    appId: '1:110367483360:web:d4b09262d27bec390a7785',
    messagingSenderId: '110367483360',
    projectId: 'eduguru-a9aff',
    authDomain: 'eduguru-a9aff.firebaseapp.com',
    storageBucket: 'eduguru-a9aff.appspot.com',
    measurementId: 'G-F7XP6DKZ8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkDOX6YLgQlK65XsCQH01y7u149US5ml0',
    appId: '1:110367483360:android:02e0c6cac62a98840a7785',
    messagingSenderId: '110367483360',
    projectId: 'eduguru-a9aff',
    storageBucket: 'eduguru-a9aff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7R2hLFbidcD-aIqgjx7Bp8lYF1_2ksmk',
    appId: '1:110367483360:ios:ae009751ef3c24f60a7785',
    messagingSenderId: '110367483360',
    projectId: 'eduguru-a9aff',
    storageBucket: 'eduguru-a9aff.appspot.com',
    iosClientId: '110367483360-l0djt5tck3i3ffm2er0s2vnibl5nbekl.apps.googleusercontent.com',
    iosBundleId: 'com.anthonyatuoha.eduGuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7R2hLFbidcD-aIqgjx7Bp8lYF1_2ksmk',
    appId: '1:110367483360:ios:bfdc9c50be0584180a7785',
    messagingSenderId: '110367483360',
    projectId: 'eduguru-a9aff',
    storageBucket: 'eduguru-a9aff.appspot.com',
    iosClientId: '110367483360-l4hgr4ka3qhq0eifjld7vr0dt3kgk10u.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduGuru.RunnerTests',
  );
}
